name: prometheus_eaton_ups_exporter tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: git config
      run: |
        git config --global user.email "eaton@exporter.com"
        git config --global user.name "Eaton Exporter"
    - name: Install dependencies
      run: |
        pip install -e ".[tests]"
    - name: flake8 linting
      run: |
        flake8
    - name: Pyre type-checking
      run: |
        pyre --noninteractive check
    - name: Test with pytest
      run: |
        pytest -vv
